### ISSUE TITLE
Can't Infer \ לא ניתן לג'נרט קובץ

### ISSUE THREAD

**Issue by UberStorm** [slp-rl/HebTTS#1]
היי חברים,
פרויקט מדהים! 

אבל לצערי משום מה לא עובד לי.
ממשיך לקבל שגיאה שקשורה במשהו שנקרא PosixPath.
אודה לעזרתכם

```
python infer.py  --checkpoint checkpoint.pt --output-dir ./out --text "היי מה נשמע"

Traceback (most recent call last):
  File "C:\HebTTS\infer.py", line 196, in <module>
    infer(
  File "C:\HebTTS\infer.py", line 46, in infer
    model, text_tokens = load_model(checkpoint_path, device)
  File "C:\HebTTS\infer.py", line 23, in load_model
    checkpoint = torch.load(checkpoint, map_location=device)
  File "C:\HebTTS\venv\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "C:\HebTTS\venv\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 962, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system
```

**Comment by UberStorm** [comment]
אוקיי, התגברתי על השגיאה של PosixPath דרך הוספת import של pathlib ולאחר מכן התאמה שלו לווינדוס:
```
from pathlib import Path
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath
```

עם זאת, עכשיו אני מקבל שגיאה חדשה כשאני מנסה לג'נרט:
```
C:\HebTTS> python infer.py  --checkpoint checkpoint.pt --output-dir ./out --text "היי מה נשמע"

C:\HebTTS\venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
C:\HebTTS\venv\lib\site-packages\torch\nn\functional.py:5504: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
VALL-E EOS [238 -> 367]
Traceback (most recent call last):
  File "C:\HebTTS\infer.py", line 199, in <module>
    infer(
  File "C:\HebTTS\infer.py", line 102, in infer
    torchaudio.save(audio_path, samples[0].cpu(), 24000)
  File "C:\HebTTS\venv\lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
  File "C:\HebTTS\venv\lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "C:\HebTTS\venv\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "C:\HebTTS\venv\lib\site-packages\soundfile.py", line 338, in write
    data = np.asarray(data)
  File "C:\HebTTS\venv\lib\site-packages\torch\_tensor.py", line 1087, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

**Comment by UberStorm** [comment]
אוקיי,
פתרתי את זה ועכשיו אפשר לג'נרט בווינדוס.
את השורה:
torchaudio.save(audio_path, samples[0].cpu(), 24000)

החלפתי ב:
torchaudio.save(audio_path, samples[0].cpu().detach(), 24000)

ועכשיו עובד.
